from typing import Protocol

from src.domain.models.entities import ExtractedEntity, ExtractedRelationship, ScoredChunk


class GraphStorePort(Protocol):
    async def store_entities(self, entities: list[ExtractedEntity]) -> None: ...
    async def store_relationships(self, relationships: list[ExtractedRelationship]) -> None: ...
    async def traverse(self, query: str, max_hops: int = 2) -> list[ScoredChunk]: ...
    async def delete_by_document(self, document_id: str) -> None: ...
