from typing import Protocol

from src.domain.models.entities import EmbeddingRecord, ScoredChunk


class VectorStorePort(Protocol):
    async def store(self, embeddings: list[EmbeddingRecord]) -> None: ...
    async def search(self, query_vector: list[float], top_k: int) -> list[ScoredChunk]: ...
    async def delete_by_document(self, document_id: str) -> None: ...
    async def find_similar(self, vector: list[float], threshold: float) -> list[ScoredChunk]: ...
